### ISSUE TITLE
got error in the noise canceling program

### ISSUE THREAD

**Issue by ddk50** [ohtaman/anneal#1]
Hi

I am trying to remove noises from my original picture using this annealing simulator
I follow your blog post (http://blog.brainpad.co.jp/entry/2017/04/20/160000) and write code as follows:
```python
# -*- coding:utf-8 -*-

import sys
import time

import numpy as np
import scipy.sparse as sp
import matplotlib.pyplot as plt

from anneal.models import ClassicalIsingModel, QuantumIsingModel
from anneal.annealers import SimulatedAnnealer, QuantumAnnealer


def callback(annealer, state_is_updated, model_is_updated):
    if annealer.iter_count % 50 == 0:
        print("{}: {}'th iter.".format(
            annealer.__class__.__name__,
            annealer.iter_count
        ))

def main(argv):
    WEIGHT = 1
    NOISED_IMAGE = plt.imread('5000/noised.png')  # 0-1の np.ndarray
    
    j = {}
    for x in range(1, NOISED_IMAGE.shape[0] - 1):
        for y in range(1, NOISED_IMAGE.shape[1] - 1):
            # 隣り合う j のみ WEIGHT を設定
            j[x, y, x, y + 1] = WEIGHT
            j[x, y, x + 1, y] = WEIGHT
    
    h = NOISED_IMAGE * 2 - 1  # 0-1 を ±1 に
    
    # j = {(0, 1): 1}
    # h = [0, 0]

    classical_satrt = time.time()
    classical_model = ClassicalIsingModel(j, h, state_size=2, beta=10)
    classical_annealer = SimulatedAnnealer(classical_model)
    classical_annealer.anneal(iter_callback=callback)
    classical_time = time.time() - classical_satrt

    quantum_start = time.time()
    quantum_model = QuantumIsingModel(j, h, state_size=2, beta=10, n_trotter=16)
    quantum_annealer = QuantumAnnealer(quantum_model)
    quantum_annealer.anneal(iter_callback=callback)
    quantum_time = time.time() - quantum_start

    print("SimulatedAnnealer annealing time: {}".format(classical_time))
    print("SimulatedAnnealer iter_count: {}".format(classical_annealer.iter_count))
    print("SimulatedAnnealer objective: {}".format(classical_model.energy()))
    print("QuantumAnnealer annealing time: {}".format(quantum_time))
    print("QuantumAnnealer iter_count: {}".format(quantum_annealer.iter_count))
    print("QuantumAnnealer objective: {}".format(quantum_model.objective_value()))
    print("QuantumAnnealer energy: {}".format(quantum_model.energy()))


if __name__ == '__main__':
    exit(main(sys.argv[1:]))
```

However, I got error as 
```
Traceback (most recent call last):
  File "simple.py", line 59, in <module>
    exit(main(sys.argv[1:]))
  File "simple.py", line 38, in main
    classical_model = ClassicalIsingModel(j, h, state_size=2, beta=10)
  File "/Users/kazushi/my-trunks/anaconda3/lib/python3.6/site-packages/anneal/models/classicalisingmodel.py", line 34, in __init__
    j = self._as_matrix(j, (self.state_size, self.state_size))
  File "/Users/kazushi/my-trunks/anaconda3/lib/python3.6/site-packages/anneal/models/classicalisingmodel.py", line 80, in _as_matrix
    for (i, j), v in list_or_dict.items():
ValueError: too many values to unpack (expected 2)
```

Any ideas?
Thanks

**Comment by ohtaman** [comment]
Thank you for your advice. 
The blog post was written with version 0.1 and some specs were changed after the post.

I forgot to document it.

**Comment by ddk50** [comment]
いやアドバイスしたんじゃなくて
アドバイスしてほしいんですが…

**Comment by ohtaman** [comment]
So, please try to use version 0.1
